; Flameshot v14 detects xdg-desktop-portal on the D-Bus session and tries to use the screenshot portal.
; No backend provides screenshot support for AwesomeWM on X11, so the call hangs for 30 seconds.
; Adding useX11LegacyScreenshot=true bypasses the portal and uses Qt's native X11 screenshot capture instead

[General]
contrastOpacity=188
;useX11LegacyScreenshot=true
